
{% set data = load_setup_py_data() %}

package:
    name: cone_balls

    version: {{ data['version'] }}

source:
    path: ../

build:
    number: '3'
    script_env:
      - TMP_NVCC_LOCATION         # Used to store multiple versions of the CUDA toolkit
    entry_points:
      - cone_balls=cone_balls:main

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
        - setuptools
        - pytorch==1.1.0
        - cudatoolkit {{cudatoolkit}}
        - torchvision
    run:
        - python
        - pytorch==1.1.0
        - cudatoolkit {{cudatoolkit}}
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

about:
    home: https://github.com/ahendriksen/cone_balls
    license_file: LICENSE.md
    summary: "A phantom generation package for cone beam CT geometries."

extra:
    maintainers:
        - Allard Hendriksen
